
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-4
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjc4NTg0NzYz","is_bot":false,"login":"kkwen123","name":"Kaiwen Tang"},"headRefName":"KaiwenBrenna-RemoveQuarter","number":44,"title":"kt - remove quarter from sections in course history table","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/44"},{"author":{"id":"MDQ6VXNlcjgxNjQ5MjU3","is_bot":false,"login":"BrennaScholte","name":"Brenna Scholte"},"headRefName":"Brenna-basicCollection","number":42,"title":"bs - create the class for the basic MongoDB collection (admin can see subject area updates)","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/42"},{"author":{"id":"MDQ6VXNlcjc3NzA5MDM1","is_bot":false,"login":"nieb100","name":"ethan nguyen"},"headRefName":"JoshEthan-searchInstructor","number":28,"title":"en/js added search for instructor","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/28"},{"author":{"id":"MDQ6VXNlcjgxNjQ5MjU3","is_bot":false,"login":"BrennaScholte","name":"Brenna Scholte"},"headRefName":"Brenna-addCourseNumber","number":27,"title":"bs - add course number search option to course description search (frontend & backend)","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/27"}]
