
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-4
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NzA5MDM1","is_bot":false,"login":"nieb100","name":"ethan nguyen"},"headRefName":"JoshEthan-bugDefaultSearch","number":60,"title":"js/en - fixed bug for default search","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/60"},{"author":{"id":"MDQ6VXNlcjg2NzAyODU5","is_bot":false,"login":"Joshuason55","name":"Joshua Son"},"headRefName":"JoshEthan-controllerSearchInstructor","number":58,"title":"js/en-added controller and tests with query","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/58"},{"author":{"id":"MDQ6VXNlcjcyODIzMTA3","is_bot":false,"login":"sshivani02","name":""},"headRefName":"ShivaniRitvi-Controller2","number":56,"title":"ss - Add GradeDataController and JobsController files along with tests","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/56"},{"author":{"id":"MDQ6VXNlcjgxNjQ5MjU3","is_bot":false,"login":"BrennaScholte","name":"Brenna Scholte"},"headRefName":"Brenna-CourseSearchForm","number":54,"title":"bs - add form for course description search with course number","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/54"},{"author":{"id":"MDQ6VXNlcjUzMTk2MzI0","is_bot":false,"login":"ritvibhatt","name":""},"headRefName":"Ritvi-CourseUtilities","number":51,"title":"rb - add CourseUtilities file for formatting course id","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/51"},{"author":{"id":"MDQ6VXNlcjc3NzA5MDM1","is_bot":false,"login":"nieb100","name":"ethan nguyen"},"headRefName":"JoshEthan-searchInstructor","number":28,"title":"en/js added search for instructor","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/28"}]
