
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-4
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjg2NzAyODU5","is_bot":false,"login":"Joshuason55","name":"Joshua Son"},"headRefName":"JoshEthan-searchInstructor","number":22,"title":"js-added professor to navbar","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/22"},{"author":{"id":"MDQ6VXNlcjc4NTg0NzYz","is_bot":false,"login":"kkwen123","name":"Kaiwen Tang"},"headRefName":"KaiwenBrennaNavCourse","number":21,"title":"KT - edited navbar and test files to combine course history and description","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/21"}]
