
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s23/proj-courses-s23-7pm-4
owner: ucsb-cs156-s23
repo_name: proj-courses-s23-7pm-4
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-fix-workflow-33-a","number":25,"title":"pc - update workflow 33 to publish stryker report even if coverage is below 100%","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/25"},{"author":{"id":"MDQ6VXNlcjcyODIzMTA3","is_bot":false,"login":"sshivani02","name":""},"headRefName":"RitviShivani-gradeData","number":23,"title":"rb/ss - add entity and repository classes for grade data","url":"https://github.com/ucsb-cs156-s23/proj-courses-s23-7pm-4/pull/23"}]
